// https://eslint.nuxt.com — generated by @nuxt/eslint
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Project-level overrides + ignores layered on top of the Nuxt defaults.
  {
    ignores: [
      // Static HTML/CSS/JS prototype — reference material, not part of the app.
      '_process/**',
      // Plan & brief docs may include code fences but aren't lintable.
      'docs/**',
    ],
  },
  {
    // Marquee is a deliberately single-word, generic ticker primitive
    // (PRO-113, ticket-mandated name). The multi-word rule guards against
    // clashing with native elements; "marquee" is a deprecated element but
    // never used here, and the component is namespaced in templates. Scope
    // the exemption to this one file rather than relaxing it globally.
    files: ['app/components/Marquee.vue'],
    rules: {
      'vue/multi-word-component-names': 'off',
    },
  },
)
