// https://eslint.nuxt.com — generated by @nuxt/eslint
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Project-level overrides + ignores layered on top of the Nuxt defaults.
  {
    ignores: [
      // Static HTML/CSS/JS prototype — reference material, not part of the app.
      '_process/**',
      // Plan & brief docs may include code fences but aren't lintable.
      'docs/**',
    ],
  },
)
